export const MAP_TARGETS: [href: string, keys: string[]][] = [
  ['amedio-jungle', ['amedio']],
  ['artonsamay-river', ['artonsamay']],
  ['bissel', ['lirtlemark', 'march-bissel']],
  ['burneal-forest', ['burneal']],
  ['celene', ['kingdom-celene']],
  ['clatspur-range', ['clatspur', 'clatspur-mountains']],
  ['county-sunndi', ['sunndi']],
  ['crystalmist-mountains', ['crystalmists']],
  ['drachensgrab-hills', ['drachensgrab']],
  ['dramidj-ocean', ['dramidj']],
  ['duchy-tenh', ['tenh']],
  ['dulsi-river', ['dulsi']],
  ['dyvers', ['free-independent-city-dyvers']],
  ['fairwind-isle', ['fairwind']],
  ['ferrond', ['viceroyalty-ferrond']],
  ['flanmi-river', ['flanmi']],
  ['fler-river', ['fler']],
  ['flinty-hills', ['flint-hills']],
  ['flotsom-island', ['flotsom']],
  ['franz-river', ['franz']],
  ['frost-barbarians', ['fruztii', 'kingdom-fruztii']],
  ['grand-duchy-geoff', ['geoff']],
  ['grandwood-forest', ['grandwood']],
  ['great-kingdom', ['aerdy', 'kingdom-aerdy']],
  ['greyhawk', ['free-city-greyhawk']],
  ['gull-cliffs', ['gullcliffs']],
  ['hold-sea-princes', ['sea-princes']],
  ['hool-river', ['hool']],
  ['ice-barbarians', ['cruski', 'cruskii', 'kingdom-cruski']],
  ['idee', ['county-idee']],
  ['irongate', ['free-city-irongate']],
  ['iuz', ['land-iuz']],
  ['jetsom-island', ['jetsom']],
  ['kewl-river', ['kewl']],
  ['kingdom-furyondy', ['furyondy']],
  ['kingdom-keoland', ['keoland']],
  ['kingdom-nyrond', ['nyrond']],
  ['lortmil-mountains', ['lortmils']],
  ['mikar-river', ['mikar']],
  ['nuther-wood', ['nutherwood']],
  ['old-river', ['old']],
  ['onnwal', ['free-state-onnwal']],
  ['perrenland', ['concatenated-cantons-perrenland']],
  ['plains-paynims', ['paynim', 'tribes-paynims']],
  ['port-toli', ['toli']],
  ['prelacy-almor', ['almor']],
  ['ratik', ['archbarony-ratik']],
  ['rel-astra', ['city-rel-astra']],
  ['ritensa-river', ['ritensa']],
  ['rushmoors', ['rushmoor']],
  ['see-medegia', ['medegia']],
  ['selintan', ['selintan-river']],
  ['sheldomar-river', ['sheldomar']],
  ['snow-barbarians', ['kingdom-schnai', 'schnai']],
  ['spindrift-isles', ['spindrifts']],
  ['sterich', ['earldom-sterich']],
  ['suss-forest', ['suss']],
  ['theocracy-pale', ['pale']],
  ['tiger-nomads', ['chakyik']],
  ['timberway-forest', ['timberway']],
  ['tuflik-river', ['tuflik']],
  ['ulek', ['ulek-provinces', 'ulek-states']],
  ['ulsprue', ['ulsprue-mountains', 'ulsprue-range']],
  ['veluna', ['archclericy-veluna']],
  ['velverdyva-river', ['highfolk-valley', 'valley-velverdyva', 'velverdyva']],
  ['veng-river', ['veng']],
  ['verbobonc', ['viscounty-town-verbobonc']],
  ['whyestil-lake', ['lake-whyestil', 'whyestil']],
  ['wolf-nomads', ['wegwiur']],
  ['yatil-mountains', ['yatils']]
]
