export const MAP_TARGETS: [href: string, keys: string[]][] = [
  ['bissel', ['march-bissel', 'lirtlemark']],
  ['celene', ['kingdom-celene']],
  ['clatspur-range', ['clatspur-mountains']],
  ['crystalmist-mountains', ['crystalmists']],
  ['duchy-tenh', ['tenh']],
  ['dyvers', ['free-independent-city-dyvers']],
  ['ferrond', ['viceroyalty-ferrond']],
  ['frost-barbarians', ['kingdom-fruztii', 'fruztii']],
  ['grand-duchy-geoff', ['geoff']],
  ['grandwood-forest', ['grandwood']],
  ['great-kingdom', ['kingdom-aerdy', 'aerdy']],
  ['greyhawk', ['free-city-greyhawk']],
  ['ice-barbarians', ['kingdom-cruski', 'cruski']],
  ['idee', ['county-idee']],
  ['irongate', ['free-city-irongate']],
  ['iuz', ['land-iuz']],
  ['kingdom-furyondy', ['furyondy']],
  ['kingdom-keoland', ['keoland']],
  ['kingdom-nyrond', ['nyrond']],
  ['lortmil-mountains', ['lortmils']],
  ['onnwal', ['free-state-onnwal']],
  ['perrenland', ['concatenated-cantons-perrenland']],
  ['plains-paynims', ['tribes-paynims']],
  ['prelacy-almor', ['almor']],
  ['ratik', ['archbarony-ratik']],
  ['rel-astra', ['city-rel-astra']],
  ['rushmoors', ['rushmoor']],
  ['sheldomar-river', ['sheldomar']],
  ['snow-barbarians', ['kingdom-schnai', 'schnai']],
  ['sterich', ['earldom-sterich']],
  ['theocracy-pale', ['pale']],
  ['tiger-nomads', ['chakyik']],
  ['veluna', ['archclericy-veluna']],
  ['velverdyva-river', ['valley-velverdyva', 'velverdyva']],
  ['verbobonc', ['viscounty-town-verbobonc']],
  ['whyestil-lake', ['whyestil']],
  ['wolf-nomads', ['wegwiur']]
]
