export const MAP_TARGETS: [href: string, keys: string[]][] = [
  ['bissel', ['march-bissel', 'lirtlemark']],
  ['celene', ['kingdom-celene']],
  ['duchy-tenh', ['tenh']],
  ['dyvers', ['free-independent-city-dyvers']],
  ['frost-barbarians', ['kingdom-fruztii', 'fruztii']],
  ['great-kingdom', ['kingdom-aerdy', 'aerdy']],
  ['greyhawk', ['free-city-greyhawk']],
  ['highfolk', ['valley-velverdyva']],
  ['ice-barbarians', ['kingdom-cruski']],
  ['idee', ['county-idee']],
  ['irongate', ['free-city-irongate']],
  ['iuz', ['land-iuz']],
  ['kingdom-furyondy', ['furyondy']],
  ['kingdom-keoland', ['keoland']],
  ['kingdom-nyrond', ['nyrond']],
  ['onnwal', ['free-state-onnwal']],
  ['perrenland', ['concatenated-cantons-perrenland']],
  ['plains-paynims', ['tribes-paynims']],
  ['prelacy-almor', ['almor']],
  ['ratik', ['archbarony-ratik']],
  ['rel-astra', ['city-rel-astra']],
  ['snow-barbarians', ['kingdom-schnai']],
  ['sterich', ['earldom-sterich']],
  ['theocracy-pale', ['pale']],
  ['tiger-nomads', ['chakyik']],
  ['veluna', ['archclericy-veluna']],
  ['verbobonc', ['viscounty-town-verbobonc']],
  ['wolf-nomads', ['wegwiur']]
]
